### LAB ASSIGNMENT 3 UCS538 DATA SCIENCE

<b>Question 1 : Extract all odd and even numbers from the given array into two separate arrays.
Also update the given array by 0 at the place of even number.</b>


In [1]:
import numpy as np
import array

In [2]:
# arr = np.arange(10)
arr = np.array([11,12,14, 13,15, 17, 19])
even_arr = np.array([])
odd_arr = np.array([])
for i in arr:
    if(i%2==0):
        even_arr= np.append(even_arr,i)
    else:
        odd_arr= np.append(odd_arr,i)
        
x = np.where(arr % 2 == 1, arr, 0)


print(arr)
print(odd_arr)
print(even_arr)
print(x)

[11 12 14 13 15 17 19]
[11. 13. 15. 17. 19.]
[12. 14.]
[11  0  0 13 15 17 19]


<b>Question 2 : Replace all odd numbers in the given array with ‘odd’ without changing original
array</b>

In [3]:
arr = np.where(arr % 2 == 1, 'odd', arr)
print(arr)

['odd' '12' '14' 'odd' 'odd' 'odd' 'odd']


<b>Question 3 : Create the following pattern using numpy inbuilt function having input array
a = 'How','Are','You'<br>output:
['How', 'How', 'How', 'Are', 'Are', 'Are', 'You', 'You', 'You',
 'How', 'Are', 'You', 'How', 'Are', 'You', 'How', 'Are', 'You']</b>

In [4]:
a = ['How', 'are', 'you']

x = np.array(a)
print(np.concatenate([np.repeat(x, 3), np.tile(x, 3)]))

['How' 'How' 'How' 'are' 'are' 'are' 'you' 'you' 'you' 'How' 'are' 'you'
 'How' 'are' 'you' 'How' 'are' 'you']


<b>Question 4: Consider the two arrays having input as alphabet, extract the common alphabet
elements from the given two arrays.</b>

In [5]:
a = np.array(['a', 'b', 'c'])
b = np.array(['c', 'd', 'e'])

print(np.intersect1d(a, b))

['c']


<b>Question 5: Write a python code to swap the last two columns of the given array also swap two
rows of the given array</b>

In [6]:
a = np.arange(25).reshape(5, 5)
print(a)
print()
#columns
temp = a[:, -1].copy()
a[:, -1] = a[:, -2]
a[:, -2] = temp
print(a)
#rows
temp = a[-1, :].copy()
a[-1, :] = a[-2, :]
a[-2, :] = temp

print()
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

[[ 0  1  2  4  3]
 [ 5  6  7  9  8]
 [10 11 12 14 13]
 [15 16 17 19 18]
 [20 21 22 24 23]]

[[ 0  1  2  4  3]
 [ 5  6  7  9  8]
 [10 11 12 14 13]
 [20 21 22 24 23]
 [15 16 17 19 18]]


<b>Question 6: Create 2D array of shape 5x3 to contain random decimal numbers between 6 and
12</b>

In [7]:
np.random.uniform(6, 12, size = (5, 3))

array([[ 7.23353884,  9.88482043,  9.43856348],
       [ 7.97590405,  7.14289564,  8.35494796],
       [ 7.76187988,  8.33755438,  8.48682349],
       [ 9.42078494,  9.07514188,  6.30762379],
       [11.90944233, 10.29751765,  6.62450755]])

<b>Question 7: Write a code to print random numbers upto 2 decimal places of numpy array</b>

In [8]:
np.linspace(1, 10, 20).round(2)

array([ 1.  ,  1.47,  1.95,  2.42,  2.89,  3.37,  3.84,  4.32,  4.79,
        5.26,  5.74,  6.21,  6.68,  7.16,  7.63,  8.11,  8.58,  9.05,
        9.53, 10.  ])

<b>Question 8: Convert the 1D IRIS to 2D array iris_2d by omitting the species text field.<br>
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'</b>

<b>Find the mean, median, standard deviation of iris's sepallength. [use above link]</b>